apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRoleBinding 
metadata: 
  name: clusterrole-binding-monitoring 
subjects: 
- kind: User 
  name: appmonitor  
  apiGroup: rbac.authorization.k8s.io 
roleRef: 
  kind: ClusterRole  
  name: clusterrole-monitoring 
  apiGroup: rbac.authorization.k8s.io
