apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding 
metadata: 
  name: read-pods 
  namespace: dev-ns 
subjects: 
- kind: User 
  name: appuser  
  apiGroup: rbac.authorization.k8s.io 
roleRef: 
  kind: Role  
  name: pod-reader  
  apiGroup: rbac.authorization.k8s.io 
